package com.example.campusrecruitmentsystem.models

data class Job(
    val title: String = "",
    val criteria: String = "",
    val company: String = "",
    val location: String = "",
    val description: String = "",
    val salary: String = ""
) {
    // No-argument constructor is automatically generated by Kotlin
}